[package]
name = "findit"
version = "0.1.0"
authors = ["Thomas <tom.bauer95@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = { version = "0.3" }
indicatif = "0.15.0"